# Site settings
title: Mohammad Amin Amjadi
description: Prsonal Page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Amin Amjadi
user_description: An experienced developer who precisely executes software development projects from concept to delivery
user_title: Software Developer
email: m.a.amjdi@gmail.com.com
twitter_username: https://twitter.com/amjadi
github_username:  https://github.com/amjadi
linkedin_username:  https://www.linkedin.com/in/aminamjadi/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
